version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /home/long/goapp/src/rec53/etc/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus'
    restart: always
    networks:
      - prometheus
    depends_on:
      - node-exporter
      - rec53

  rec53:
    image: rec53
    volumes:
      - ./log/:/dist/log/
    ports:
      - 5353:5353
      - 5353:5353/udp
      - 9999:9999/tcp  # for prometheus
    restart: always
    build: ../ # build from Dockerfile
    networks:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - prometheus
networks:
  prometheus:
    driver: bridge