// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package server

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dnsCacheCacheKey struct {
	_     structs.HostLayout
	Qname [255]uint8
	Pad   uint8
	Qtype uint16
}

type dnsCacheCacheValue struct {
	_        structs.HostLayout
	ExpireTs uint64
	RespLen  uint32
	Response [512]uint8
}

// loadDnsCache returns the embedded CollectionSpec for dnsCache.
func loadDnsCache() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsCacheBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dnsCache: %w", err)
	}

	return spec, err
}

// loadDnsCacheObjects loads dnsCache and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsCacheObjects
//	*dnsCachePrograms
//	*dnsCacheMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsCacheObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDnsCache()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsCacheSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsCacheSpecs struct {
	dnsCacheProgramSpecs
	dnsCacheMapSpecs
	dnsCacheVariableSpecs
}

// dnsCacheProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsCacheProgramSpecs struct {
	XdpDnsCache *ebpf.ProgramSpec `ebpf:"xdp_dns_cache"`
}

// dnsCacheMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsCacheMapSpecs struct {
	CacheMap   *ebpf.MapSpec `ebpf:"cache_map"`
	ScratchMap *ebpf.MapSpec `ebpf:"scratch_map"`
	XdpStats   *ebpf.MapSpec `ebpf:"xdp_stats"`
}

// dnsCacheVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsCacheVariableSpecs struct {
}

// dnsCacheObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsCacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsCacheObjects struct {
	dnsCachePrograms
	dnsCacheMaps
	dnsCacheVariables
}

func (o *dnsCacheObjects) Close() error {
	return _DnsCacheClose(
		&o.dnsCachePrograms,
		&o.dnsCacheMaps,
	)
}

// dnsCacheMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsCacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsCacheMaps struct {
	CacheMap   *ebpf.Map `ebpf:"cache_map"`
	ScratchMap *ebpf.Map `ebpf:"scratch_map"`
	XdpStats   *ebpf.Map `ebpf:"xdp_stats"`
}

func (m *dnsCacheMaps) Close() error {
	return _DnsCacheClose(
		m.CacheMap,
		m.ScratchMap,
		m.XdpStats,
	)
}

// dnsCacheVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsCacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsCacheVariables struct {
}

// dnsCachePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsCacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsCachePrograms struct {
	XdpDnsCache *ebpf.Program `ebpf:"xdp_dns_cache"`
}

func (p *dnsCachePrograms) Close() error {
	return _DnsCacheClose(
		p.XdpDnsCache,
	)
}

func _DnsCacheClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnscache_bpfeb.o
var _DnsCacheBytes []byte
