package server

const (
	STATE_INIT = iota
	CACHE_LOOKUP
	CLASSIFY_RESP
	EXTRACT_GLUE
	LOOKUP_NS_CACHE
	QUERY_UPSTREAM
	RETURN_RESP
	MAX_STATE
)

const (
	STATE_INIT_COMMON_ERROR = -1
	STATE_INIT_NO_ERROR     = 0
	STATE_INIT_FORMERR      = 1
)

const (
	CACHE_LOOKUP_COMMON_ERROR = -1
	CACHE_LOOKUP_HIT          = 0
	CACHE_LOOKUP_MISS         = 1
)

const (
	CLASSIFY_RESP_COMMON_ERROR = -1
	CLASSIFY_RESP_GET_ANS      = 0
	CLASSIFY_RESP_GET_CNAME    = 1
	CLASSIFY_RESP_GET_NS       = 2
	CLASSIFY_RESP_GET_NEGATIVE = 3
)

const (
	EXTRACT_GLUE_COMMON_ERROR = -1
	EXTRACT_GLUE_EXIST        = 0
	EXTRACT_GLUE_NOT_EXIST    = 1
)

const (
	LOOKUP_NS_CACHE_COMMON_ERROR = -1
	LOOKUP_NS_CACHE_HIT          = 0
	LOOKUP_NS_CACHE_MISS         = 1
)

const (
	QUERY_UPSTREAM_COMMON_ERROR = -1
	QUERY_UPSTREAM_NO_ERROR     = 0
)

const (
	RETURN_RESP_COMMON_ERROR = -1
	RETURN_RESP_NO_ERROR     = 0
)
